name: CI Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  get-version:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
    container: node:${{ matrix.node-version }}-alpine
    steps:
      - run: node --version
