name: CI Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  get-version:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [node:14-alpine, node:16-alpine, node:18-alpine, node:20-alpine]
    container: ${{ matrix.node-version }}
    steps:
      - run: node --version
