name: CI Test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  node-14:
    runs-on: self-hosted
    container: node:14-alpine
    steps:
      - run: node --version
  node-16:
    runs-on: self-hosted
    container: node:16-alpine
    steps:
      - run: node --version
  node-18:
    runs-on: self-hosted
    container: node:18-alpine
    steps:
      - run: node --version
  node-20:
    runs-on: self-hosted
    container: node:20-alpine
    steps:
      - run: node --version
